//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebUI.Services.Payments.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Fund
    {
        public int FundId { get; set; }
        public System.Guid FundGuid { get; set; }
        public System.Guid AccountGuid { get; set; }
        public string Name { get; set; }
        public decimal Amount { get; set; }
        public decimal GoalAmount { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public System.DateTime ReleaseOn { get; set; }
        public decimal Balance { get; set; }
        public int Frequency { get; set; }
    }
}
